#RemediationPlaybook
---

- hosts: appservers:dbservers
  become: true 
  tasks:
          - name: Reboot server
            reboot:
                    reboot_timeout: 3600
            tags:
                    - reboot

- hosts: dbservers
  become: true
  tasks:
          - name: Folder Clean-up
            command: 
                    find /var -name "*.log" \( \( -size +50M -mtime +7 \) -o -mtime +30 \) -exec truncate {} --size 0 \;
            when: "item.mount == '/var' and ( item.size_available < item.size_total * 0.2 )"
            with_items: ansible_mounts

- hosts: appservers
  become: true
  tasks:
          - name:
            service:
                    name: httpd
                    state: started
